### ISSUE TITLE
Fix actions for Julia

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/cross_language_projects#5]
Upstream issue that may be relevant: https://github.com/quarto-dev/quarto-cli/issues/10837

Any ideas @evetion? Hard to debug at this stage..

**Comment by cderv** [comment]
> Upstream issue that may be relevant: https://github.com/quarto-dev/quarto-cli/issues/10837

Just a heads up that this upstream issue is not relevant as your document is not using `engine: julia` from Quarto. 

You are running Julia cell in a document with Python and R too. This means that by default `engine: knitr` will be used by Quarto (because of R cell presence). 

It implies 
- Python cells are run through **reticulate**
- Julia celles are run through **JuliaCall** by default. 

You need to be sure both are correctly setup regarding how to find Julia. Especiall **JuliaCall** needs to work specifically with the R version through `RCall`. It may be interested to add a configure step in your workflow where R would call `julia <- julia_setup()` to be sure it finds all the necessary tool. 

Hope it helps

**Comment by Robinlovelace** [comment]
Thanks @cderv that is v. helpful, will give it a go..

**Comment by Robinlovelace** [comment]
Trying using the Julia kernel in #7 https://quarto.org/docs/computations/julia.html

**Comment by cderv** [comment]
I don't know exactly what you are trying to do here but whatever the solution, you need to do the correct setup. 

- If using **knitr**, I would look at `julia_setup()` R function (https://non-contradiction.github.io/JuliaCall/reference/julia_setup.html) and call it once before doing `quarto render` (or call it in a setup chunk) so that configuration is done ok. Especially `julia_setup(rebuild = TRUE)` may be needed, or `JULIA_HOME` needs to be set. 
	- Doing this in a specific CI step with R will give your confirmation that R is correctly setup to call Julia. This is prerequisite for knitr to call it, and so for Quarto to work. 

- If Using jupyter to use Julia, you need to setup the kernels. We document this at https://quarto.org/docs/computations/julia.html#installation. This is required for Jupyter to find the right kernal with JUpyter which will call Julia. Then Julia package needs to be available in the right environment. 

- If Using quarto `engine: julia`, there is no jupyter involved. Julia needs to be installed, and JUlia environment project needs to be configured at the Quarto project level. The julia engine will call `julia --project=@.` and so use the closest `Project.toml`, and assumes good practice to have an environment at project level. 

I hope this helps clarify. Note that you can't mix 3 options in one document. Either `engine: knitr` or `engine: <julia-kernel-name>` or `engine: julia`.

**Comment by Robinlovelace** [comment]
Thanks for this @cderv. FYI @evetion has it working on mac os actions: https://github.com/evetion/cross_language_projects

Seems to us that maybe there's something about R/Julia interop that fails on Linux, probably not Quarto's fault, will be good to properly diagnose and with Julia people like Marten onboard we have hopes of doing that.

**Comment by Robinlovelace** [comment]
Results looking good, rendering R, Julia, Python versions, go Quarto! https://www.evetion.nl/cross_language_projects/demo.html

Will be really good to get this working on Linux one day, if anyone has any ideas how let us know.

**Comment by cderv** [comment]
> Seems to us that maybe there's something about R/Julia interop that fails on Linux, probably not Quarto's fault, will be good to properly diagnose and with Julia people like Marten onboard we have hopes of doing that.

Oh this reminds me of 
- https://github.com/Non-Contradiction/JuliaCall/issues/192
and Quarto report 
- https://github.com/quarto-dev/quarto-cli/issues/7752

So possibly this is the problem. 

This new package https://github.com/stefan-m-lenz/JuliaConnectoR could be a better alternative, but we still need to add a knitr engine to it (https://github.com/stefan-m-lenz/JuliaConnectoR/issues/28)

**Comment by Robinlovelace** [comment]
This sounds really great, thanks for sharing, following with interest!
